---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.336.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: nodejs/node
  version: 22.15.0 # renovate: depName=nodejs/node
- name: pnpm/pnpm@v10.10.0
- name: biomejs/biome@cli/v1.9.4
- name: google/yamlfmt@v0.16.0
- name: tamasfe/taplo@0.9.3
- name: evilmartians/lefthook@v1.11.11
- name: rhysd/actionlint@v1.7.7
- name: suzuki-shunsuke/ghalint@v1.3.0
- name: suzuki-shunsuke/pinact@v3.0.1
- name: editorconfig-checker/editorconfig-checker@v3.2.1
- name: oxc-project/oxc/oxlint@oxlint_v0.16.0
