---
name: Setup pnpm
description: Setup pnpm by using cache and environment variables
runs:
  using: composite
  steps:
  - name: Get Cache Directory
    id: pnpm-cache-dir
    shell: bash
    run: |-
      echo "store-path=$(pnpm store path)" >> $GITHUB_OUTPUT
  - name: Restore Cache
    id: cache-primes-restore
    uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      key: pnpm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      path: |-
        ${{ steps.pnpm-cache-dir.outputs.store-path }}
  - name: Install Packages
    shell: bash
    run: |-
      pnpm install --frozen-lockfile
  - name: Get Default Branch
    id: gh
    env:
      GH_TOKEN: ${{ github.token }}
    shell: bash
    run: echo default_branch_ref_name="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)" >> "$GITHUB_OUTPUT"
  - name: Show Branch
    shell: bash
    run: |-
      echo "REF_NAME: '${REF_NAME}'"
      echo "DEFAULT_BRANCH: '${DEFAULT_BRANCH}'"
    env:
      REF_NAME: ${{ github.ref_name }}
      DEFAULT_BRANCH: ${{ steps.gh.outputs.default_branch_ref_name }}
  - name: Save Cache
    if: github.ref_name == steps.gh.outputs.default_branch_ref_name && steps.cache-primes-restore.outputs.cache-hit != 'true'
    uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
      path: |-
        ${{ steps.pnpm-cache-dir.outputs.store-path }}
