---
name: CI
on:
  push:
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup pnpm
      uses: ./.github/actions/setup-pnpm
    - name: Running Lint
      run: pnpm run lint
    - name: Running Test
      run: pnpm run test
