---
name: CI
on:
  push:
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      with:
        aqua_version: v2.43.0
        aqua_opts: -a
    - name: Setup Node.js
      run: pnpm install --frozen-lockfile
    - name: Running Lint
      run: pnpm run lint
    - name: Running Test
      run: pnpm run test
